# Generated by Django 3.2.8 on 2021-11-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20211028_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='imgs')),
            ],
        ),
    ]
