# Generated by Django 3.2.8 on 2021-11-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFormWithFileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload')),
            ],
        ),
    ]
