# Generated by Django 3.2.8 on 2021-11-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20211103_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithfilefield',
            name='file_field',
            field=models.FileField(null=True, upload_to='upload'),
        ),
    ]
