# Generated by Django 3.2.8 on 2021-11-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_modelwithfilefield_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='userComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('article_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
    ]
