# Generated by Django 3.2.8 on 2021-11-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_article_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='c_user',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='创建人'),
        ),
    ]
