# Generated by Django 3.2.8 on 2021-11-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20211113_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='c_user',
            new_name='user',
        ),
    ]
