# Generated by Django 3.2.8 on 2021-11-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_alter_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
