# Generated by Django 3.2.8 on 2021-11-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20211116_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='publish_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='发布时间'),
        ),
    ]
